### ISSUE TITLE
Error setting Margin Type & Leverage

### ISSUE THREAD

**Issue by IsaTTeN** [cuongitl/python-bitget#11]
Hello

First thing first, thank you for this wrapper. It's fantastic

I am experiencing a problem when I try to change the Margin Mode and Leverage in the same go. I am getting this error: "API Request Error(code=40409): wrong format"

The code that I am executing is this:

```
 try:
       print("Changing Margin Type")
       margin = session.mix_adjust_margintype(symbol="SBTCSUSDT_SUMCBL",marginCoin="SUSDT",marginMode="fixed")
       print(margin)
 except Exception as inst:
 print(inst)

 try:
       print("Changink Leverage")
       apal = session.mix_adjust_leverage(symbol="SBTCSUSDT_SUMCBL", marginCoin="SUSDT", leverage="3", holdSide="long")
       print(apal)
 except Exception as inst:
 print(inst)

```

If I execute that code a second time I don´t get any error

Thnak you very much for your hard work

**Comment by cuongitl** [comment]
> Hello
> 
> First thing first, thank you for this wrapper. It's fantastic
> 
> I am experiencing a problem when I try to change the Margin Mode and Leverage in the same go. I am getting this error: "API Request Error(code=40409): wrong format"
> 
> The code that I am executing is this:
> 
> ```
>  try:
>        print("Changing Margin Type")
>        margin = session.mix_adjust_margintype(symbol="SBTCSUSDT_SUMCBL",marginCoin="SUSDT",marginMode="fixed")
>        print(margin)
>  except Exception as inst:
>  print(inst)
> 
>  try:
>        print("Changink Leverage")
>        apal = session.mix_adjust_leverage(symbol="SBTCSUSDT_SUMCBL", marginCoin="SUSDT", leverage="3", holdSide="long")
>        print(apal)
>  except Exception as inst:
>  print(inst)
> ```
> 
> If I execute that code a second time I don´t get any error
> 
> Thnak you very much for your hard work

Hello,
I tried one by one your code. It's ok.
This issue by your api.
