### ISSUE TITLE
ModuleNotFoundError: No module named 'pybitget'

### ISSUE THREAD

**Issue by Paul-Bowry** [cuongitl/python-bitget#16]
Hi there, I am trying to get this code to run but without any success. I have installed the module: pip3 install python-bitget

from pybitget import Client

api_key = "your-api-key"
api_secret = "your-secret-key"
api_passphrase = "your-api-passphrase"

client = Client(api_key, api_secret, passphrase=api_passphrase)
result = client.mix_get_accounts(productType='UMCBL')
print(result)

**Comment by cuongitl** [comment]
please try re-install the module.
