### ISSUE TITLE
Cannot use limit parameter in mix_get_candles method

### ISSUE THREAD

**Issue by aoki-h-jp** [cuongitl/python-bitget#17]
Since the "limit" parameter is not accepted, it is not possible to retrieve information other than 100 cases.
https://github.com/cuongitl/python-bitget/blob/master/pybitget/client.py#L187-L203
According to the API documentation, it is possible to retrieve up to 1000 cases, but this is inconvenient when retrieving such a number of candles.
Please change it so that it can accept additional arguments.

**Comment by cuongitl** [comment]
New update with Accept additional arguments.

**Comment by aoki-h-jp** [comment]
Thanks for the quick response!
